# Changes here will be overwritten by Copier.
_commit: 1.8.6
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2023'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: griffe-pydantic
project_description: Griffe extension for Pydantic.
project_name: griffe-pydantic
public_release: true
python_package_command_line_name: ''
python_package_distribution_name: griffe-pydantic
python_package_import_name: griffe_pydantic
repository_name: griffe-pydantic
repository_namespace: mkdocstrings
repository_provider: github.com

